# Generated by Django 2.2 on 2019-06-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('street', models.CharField(max_length=128, verbose_name='Улица')),
                ('building', models.CharField(max_length=10, verbose_name='Дом')),
                ('office', models.SmallIntegerField(null=True, verbose_name='Квартира')),
                ('metro', models.CharField(max_length=128, verbose_name='Метро')),
            ],
        ),
    ]
