# Generated by Django 2.2 on 2019-06-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeduser', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PRD', 'обрабатывается'), ('ACP', 'принят'), ('RJC', 'отклонен'), ('PD', 'оплачен'), ('RDY', 'готов к выдаче'), ('CND', 'отменен')], default='PRD', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeduser.ProducerProfile')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeduser.ConsumerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='orders.Order')),
            ],
        ),
    ]
