# Generated by Django 2.2 on 2019-06-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без категории', max_length=64, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('energy', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('recipe', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('snippet', models.CharField(blank=True, max_length=125, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/meals/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Category')),
                ('ingredients', models.ManyToManyField(to='menu.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
    ]
